apiVersion: v1
data:
  username: '{{ .Values.secret.git.username }}'
  password: '{{ .Values.secret.git.password }}'
kind: Secret
metadata:
  name: tx-application-git
  namespce: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "fluxcd.labels" . | nindent 4 }}
type: Opaque