apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ include "fluxcd.fullname" . }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "fluxcd.labels" . | nindent 4 }}
spec:
  chart:
    spec:
      chart: {{ .Values.helmRelease.chart }}
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        {{- if .Values.helmRelease.sourceRef }}
        name: {{ .Values.helmRelease.sourceRef.name | default (include "fluxcd.fullname" .) }}
        namespace: {{ .Values.helmRelease.sourceRef.namespace | default .Release.Namespace }}
        {{- else }}
        name: {{ include "fluxcd.fullname" . }}
        namespace: {{ .Release.Namespace }}
        {{- end }}        
  install:
    createNamespace: {{ .Values.helmRelease.install.createNamespace }}
  interval: {{ .Values.helmRelease.interval }}
  releaseName: {{ .Values.helmRelease.releaseName | default (include "fluxcd.fullname" .) }}
  targetNamespace: {{ .Values.helmRelease.targetNamespace | default .Release.Namespace }}
  values:
    {{- toYaml .Values.helmValues | nindent 4 }}
