apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fluxcd.fullname" . }}-image
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "fluxcd.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: '{{ .Values.secret.image.dockerconfigjson }}'