apiVersion: v1
kind: Secret
metadata:
  name: tx-application-image
  labels:
    {{- include "fluxcd.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: '{{ .Values.secret.image.dockerconfigjson }}'