# Default values for nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: tiexiang.io/app/tx-nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.0"



service:
  annotations: 
    lb.kubesphere.io/v1alpha1: openelb
  type: LoadBalancer
  nodePort: 31008
  nodePort2: 31010
  nodePort3: 31011

window:
  k8surl: "192.168.3.31"

livegbs:
  proxyip: "192.168.3.210"
  proxyport: "10000"

miniodns: minio.minio-system
gatewaydns: tx-gateway.manager-system