# Default values for auth.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 192.168.1.204:30002/app/tx-auth-test
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: v1.0

resources:
  limits:
    memory: 5Gi
  requests:
    memory: 5Gi

service:
  type: NodePort
  port: "31002"
  nodePort: "31005"

configMapName: nacos-configmap

initimage:
  repository: 192.168.1.211:30002/initnacos/auth
  tag: latest
  pullPolicy: IfNotPresent

# Nacos configuration
nacos:
  url: "http://192.168.1.211:30000/nacos/v1/cs/configs"
  tenant: "dev"
  dataId: "tx-auth.yaml"
  group: "DEFAULT_GROUP"

# MySQL configuration
mysql:
  url: "jdbc:mysql://mysql-i-estpeb.mysql:3306/tx_auth?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&allowMultiQueries=true&autoReconnect=true"
  username: "root"
  password: "supersecret"
  driver: "com.mysql.cj.jdbc.Driver"

# Redis configuration
redis:
  node: "redis-c-n0lpse-leader-external-service.redis"
  port: "6379"
  password: ""

app:
  name: "tx-auth"
  serverPort: "31102"