# Default values for auth.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: tiexiang.io/app/tx-auth
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: v1.0

resources:
  limits:
    memory: 5Gi
  requests:
    memory: 5Gi

service:
  type: NodePort
  port: "31002"


nacos:
  group: DEFAULT_GROUP
  namespace: base-test
  server: nacos-cs.nacos-system

