namespace: defalut
projectAddress: gitlab.gxtxkj.com
projectGroup: application/progress-web
project: tx-progress-web
projectBranch: nanjingbei2
repositoryAddress: registry.gxtxkj.com

# 定义gitRepository
gitRepository:
  url: https://gitlab.gxtxkj.com/application/progress-web/tx-progress-web.git
  ref: 
    # branch: nanjingbei2
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/deploy/
  secretRef:
    enabled: true
  #   name: tx-application-git

# 定义helmRelease
helmRelease:
  chart: deploy
  interval: 1m0s
  # releaseName: progress-web
  # targetNamespace: progress-nanjingbei2
  install:
    createNamespace: true
  sourceRef:
    enabled: true
  #   name: progress-nanjingbei2-progress-web
    # namespace: progress-nanjingbei2

# 定义helmValues,helmRelease中helm chart的value内容
# 通常通过value file的形式传递
helmValues: {}
  # ingress:
  #   tls:
  #     secretName: progress-tls
  #     host: progress-nanjingbei2.gxtxkj.com
  #   className: "nginx"
  #   hosts:
  #     - host: progress-nanjingbei2.gxtxkj.com
  #       paths:
  #         - path: /
  #           pathType: ImplementationSpecific
  #     - host: progress-nanjingbei2.inner.gxtxkj.com
  #       paths:
  #         - path: /
  #           pathType: ImplementationSpecific
  # imagePullSecrets:
  #   name: tx-application-image
  # image:
  #   repository: registry.gxtxkj.com/application/progress-web/tx-progress-web # {"$imagepolicy": "progress-nanjingbei2:progress-nanjingbei2-progress-web:name"}
  #   tag: nanjingbei2-fb87bba-1741155743 # {"$imagepolicy": "progress-nanjingbei2:progress-nanjingbei2-progress-web:tag"}

# 定义imagePolicy
imagePolicy:
  filterTags:
    # pattern: '^nanjingbei2-[a-fA-F0-9]+-(?P<ts>.*)'  # Change as needed
    extract: '$ts'
  policy:
    numerical:
      order: asc

# 定义imageRepository
imageRepository:
  # image: registry.gxtxkj.com/application/progress-web/tx-progress-web
  interval: 5m0s
  secretRef:
    enabled: true
    # name: tx-application

secret:
  git: 
    password: Z2xkdC1EUWZwbmNZaGRrVWFnY3pnLXNyQQ==
    username: dHgtYXBwbGljYXRpb24=
  image:    
    dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5neHR4a2ouY29tIjp7InVzZXJuYW1lIjoidHgtYXBwbGljYXRpb24iLCJwYXNzd29yZCI6ImdsZHQtRFFmcG5jWWhka1VhZ2N6Zy1zckEiLCJhdXRoIjoiZEhndFlYQndiR2xqWVhScGIyNDZaMnhrZEMxRVVXWndibU5aYUdSclZXRm5ZM3BuTFhOeVFRPT0ifX19