apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        command: ["java","-Dfile.encoding=utf-8", "-jar", "/app/tx-manager.jar"]
        ports:
        - containerPort: {{ .Values.containerPort }}
        envFrom:
        - configMapRef:
            name: {{ .Values.nacosConfigMapName }}
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory }}
          requests:
            memory: {{ .Values.resources.requests.memory }}
        volumeMounts:
        - name: log
          mountPath: /app/logs
      volumes:
        - name: log
          persistentVolumeClaim:
            claimName: {{ .Values.pvcName }}