# Default values for manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 192.168.1.204:30002/app/tx-manager-test
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.0"

initimage:
  repository: 192.168.1.211:30002/initnacos/manager
  tag: latest
  pullPolicy: Always

# Nacos configuration
nacos:
  dataId: "tx-manager.yaml"

# Application configuration
app:
  name: "tx-manager"
  serverPort: "31101"

# Device configuration
device:
  mqttImageId: "sha256:cac0e703f48b6ef0d760e02eb2bc1af9075dcfdc321f4760eb60518f4172a0ef"
  mqttImageName: "tiexiang.io/tiexiang/bcsu-image:latest"
  publishServerImage: "publish-server:latest"
  ckDatabaseName: "default"
  levelSeconds:
    lever0: "12000"
    lever1: "600"
    lever2: "300"
    lever3: "180"
    lever4: "60"
    lever5: "30"
    lever6: "10"
  statLoginUsername: "admin"
  statLoginPassword: "123456"

# Service and deployment configurations
service:
  port: 31101

resources:
  limits:
    memory: 5Gi
  requests:
    memory: 5Gi


configMapName: nacos-configmap