apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fcu.fullname" . }}
  labels:
    {{- include "fcu.labels" . | nindent 4 }}
data:
  config.json: |
    {{- .Values.configMap.data | nindent 4 }}
  CameraSet.json: |
    {{- index .Values.configMap "CameraSet.json" | nindent 4 }}
