apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fcu.fullname" . }}-fcu
  labels:
    {{- include "fcu.labels" . | nindent 4 }}
data:
  config.json: |
    {{- index .Values.configMap "config.json" | nindent 4 }}
  CameraSet.json: |
    {{- index .Values.configMap "CameraSet.json" | nindent 4 }}
