apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fcu.fullname" . }}-fcu
  labels:
    {{- include "fcu.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configMap }}
  {{- if ne $key "data" }}
  {{ $key }}: |
{{ $value | nindent 4 }}
  {{- end }}
  {{- end }}
