apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fcu.fullname" . }}
  labels:
    {{- include "fcu.labels" . | nindent 4 }}
data:
  config.json: |
    {{- .Values.configMap.data | nindent 4 }}
  FcuConfig.json: |
    {{- .Values.configMap.CameraSet | fromJson | toYaml | nindent 4 }}
