apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fcu.fullname" . }}
  labels:
    {{- include "fcu.labels" . | nindent 4 }}
    {{ .Release.Namespace}}: {{ include "fcu.fullname" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "fcu.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fcu.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fcu.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: publish-server
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- with .Values.publishServer }}
          image: {{ .image.name }}
          imagePullPolicy: {{ .image.pullPolicy }}
          {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 10Mi
          volumeMounts:
            - mountPath: /app/config/config.json
              name: config
              subPath: config.json
            - mountPath: /app/data
              name: data           
          {{- with .Values.volumeMounts }}              
            {{- toYaml . | nindent 12 }}
          {{- end }}   
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/bash
                  - '-c'
                  - sleep 10 
        - name: fcu-server
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- with .Values.fcuServer }}
          image: {{ .image.name }}
          imagePullPolicy: {{ .image.pullPolicy }}
          {{- end }}          
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- if .Values.resources }}
            {{- with .Values.resources }}
            limits:
              cpu: {{ .limits.cpu }}
              memory: {{ .limits.memory }}
              {{- if .limits.gpu }}
              nvidia.com/gpu: {{ .limits.gpu | quote }}
              {{- end }}
            requests:
              cpu: {{ .requests.cpu }}
              memory: {{ .requests.memory }}
            {{- end }}
            {{- end }}
          volumeMounts:
            - mountPath: /app/data
              name: data
            - mountPath: /app/config/FcuConfig.json
              name: fcu-config
              subPath: FcuConfig.json
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}    
      volumes:
        - name: config
          configMap:
            name: {{ include "fcu.fullname" . }}
            items:
              - key: config.json
                path: config.json
            defaultMode: 420
        - name: fcu-config
          configMap:
            name: {{ include "fcu.fullname" . }}
            items:
              - key: FcuConfig.json
                path: FcuConfig.json
            defaultMode: 420
        - name: data
          {{- with .Values.persistentVolumeClaim.data }}
          {{- if .enabled }}
          persistentVolumeClaim:
            claimName: {{  .claimName | default (printf "%s-%s" (include "fcu.fullname" $) "data") }}
          {{- else }}
          emptyDir: {}
          {{- end }}
          {{- end }}
        {{- with .Values.volumes }}             
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: "tiexiang.io/edge-node"
                    operator: In
                    values:
                      - "true"
                  - key: "tiexiang.io/station-code"  
                    operator: In  
                    values:  
                      - {{ . | quote }}
      {{- end }}      
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
