replicaCount: 1

image:
  repository: 192.168.1.204:30002/app/tx-gateway-test
  tag: v1.0
  pullPolicy: Always

resources:
  limits:
    memory: 5Gi
  requests:
    memory: 5Gi

svcName: tx-gateway
service:
  type: NodePort
  port: 31007
  nodePort: 31007

pvcName: gateway-log
persistence:
  enabled: true
  storageClass: local
  accessMode: ReadWriteOnce
  size: 1Gi

name: tx-gateway
configMapName: nacos-configmap
