apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eesu.fullname" . }}
  labels:
    {{- include "eesu.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "eesu.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "eesu.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      initContainers:
        - name: eesu-init
          image: "{{ .Values.initimage.repository }}:{{ .Values.initimage.tag }}"
          imagePullPolicy: {{ .Values.initimage.pullPolicy }}
          command: ["python3", "/app/eesu.py"]
          volumeMounts:
            - name: {{ .Values.configMapName }}
              mountPath: /app/config  # 容器中的路径
          env:
            - name: DATA_ID
              value: {{ .Values.nacos.dataId | quote }}
            - name: MQTT_CLIENT_ID
              value: {{ .Values.mqtt.clientId | quote}}
            - name: MQTT_QOS
              value: {{ .Values.mqtt.qos | quote}}
            - name: MQTT_TOPIC
              value: {{ .Values.mqtt.topic | quote}}
            - name: APP_NAME
              value: {{ .Values.app.name | quote}}
            - name: SERVER_PORT
              value: {{ .Values.app.serverPort | quote}}
            - name: NACOS_GROUP
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMapName }}
                  key: NACOS_GROUP
            - name: NACOS_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMapName }}
                  key: NACOS_NAMESPACE
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["java","-Dfile.encoding=utf-8", "-jar", "/app/tx-eesu.jar"]
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Values.configMapName }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: {{ .Values.configMapName }}
          configMap:
            name: {{ .Values.configMapName }}
