apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eesu.fullname" . }}
  labels:
    {{- include "eesu.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "eesu.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "eesu.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["java","-Dfile.encoding=utf-8", "-jar", "/app/tx-eesu.jar"]
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: NACOS_GROUP
              value: {{ .Values.nacos.group | quote }}
            - name: NACOS_NAMESPACE
              value: {{ .Values.nacos.namespace | quote }}
            - name: NACOS_SERVER_ADDR
              value: {{ .Values.nacos.server | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

