apiVersion: batch/v1
kind: Job
metadata:
  name: allconfig
spec:
  template:
    spec:
      containers:
        - name: nacos-config
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["bash", "-c", "python3 create-db.py && python3 gateway.py && \
                    python3 emqx-api.py && python3 eesu.py && python3 dmsu.py && \
                    python3 auth.py && python3 push.py"]
          volumeMounts:
            - name: nacosconfigmap
              mountPath: /app/config  # 容器中的路径
          env:
          - name: NACOS_GROUP
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMapName }}
                  key: NACOS_GROUP
            - name: NACOS_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMapName }}
                  key: NACOS_NAMESPACE
      volumes:
        - name: nacosconfigmap
          configMap:
            name: {{ .Values.name }}
      restartPolicy: OnFailure
  backoffLimit: 3
