# Default values for eesu.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 192.168.3.31:30002/new/tx-eesu-test
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.0"

# Deployment and service configurations
service:
  port: 31103

resources:
  limits:
    memory: 5Gi
  requests:
    memory: 5Gi
    
configMapName: nacos-configmap