# Default values for push.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 192.168.1.204:30002/app/tx-push-test
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.0"

initimage:
  repository: 192.168.1.211:30002/initnacos/push
  tag: latest
  pullPolicy: IfNotPresent
# Nacos 配置
nacos:
  url: "http://192.168.1.211:30000/nacos/v1/cs/configs"
  tenant: "dev"
  dataId: "tx-push.yaml"
  group: "DEFAULT_GROUP"

# Redis 配置
redis:
  node: "redis-c-n0lpse-leader.redis"
  port: "6379"
  password: ""

# 应用程序配置
app:
  name: "tx-push"
  serverPort: "31104"

service:
  port: "31004"

resources:
  limits:
    memory: 5Gi
  requests:
    memory: 5Gi

persistence:
  enabled: true
  storageClass: local
  accessMode: ReadWriteOnce
  size: 1Gi

configMapName: nacos-configmap