# values.yaml
name: nacos-configmap

nacos:
  group: DEFAULT_GROUP
  namespace: base-test

image:
  repository: tiexiang.io/app/tx-nacosconfig:v1.0
  pullPolicy: IfNotPresent #Always
  # Overrides the image tag whose default is the chart appVersion.

aesu:
  dataid: "tx-aesu.yaml"
  appname: "tx-aesu"
  serverport: "31106"

auth:
  dataid: "tx-auth.yaml"
  appname: "tx-auth"
  serverport: "31102"

mysql:
  database: "tx_auth,tx_manager"
  initDB:
  #   nodeSelector:
  #     kubernetes.io/hostname: worker1
    mysqlData: {}
  #     path: /mysql/backup_data
  #     file: mysql_backup.tar.gz

dmsu:
  dataid: "tx-dmsu.yaml"
  appname: "tx-dmsu"
  serverport: "31101"

bcsu:
  imagename: "tiexiang.io/bcsu/bcsu-image:v1.0.12"

mqtt:
  username: "manager"
  password: "manager"
  clientid: "mqtt-client-id"
  qos: "2"
  topic: "$queue/exception/#"

publish:
  image: "publish-server:v1.0.6"

ck:
  databaseName: "default"

levels:
  level0: "12000"
  level1: "600"
  level2: "300"
  level3: "180"
  level4: "60"
  level5: "30"
  level6: "10"

statview:
  username: "admin"
  password: "123456"

expiration:
  days: "15"
  level: "3"

eesu:
  dataid: "tx-eesu.yaml"
  appname: "tx-eesu"
  serverport: "31103"
  minuteOffset: "30"

dayoffset: "14"

msg:
  level: "4"

emqx:
  ptopic: "#"
  stopic: "#"
  atopic: "#"
  ppermission: "allow"
  spermission: "allow"
  apermission: "allow"

gateway:
  dataid: "tx-gateway.yaml"
  appname: "tx-gateway"
  serverport: "31100"

push:
  dataid: "tx-push.yaml"
  appname: "tx-push"
  serverport: "31104"

statistic:
  dataid: "tx-statistic.yaml"
  appname: "tx-statistic"
  serverport: "31107"

wrapper:
  dataid: "tx-wrapper-api.yaml"

http:
  connectTimeout: "30"
  readTimeout: "30"
  writeTimeout: "30"
helm:
  repoName: "tx_helm_charts"
  configPath: "/tmp/helm-config/"
  fcuChartName: "fcu"
  bcsuChartName: "bcsu"
  caCertPath: "/run/secrets/kubernetes.io/serviceaccount/ca.crt"
  namespacePath: "/run/secrets/kubernetes.io/serviceaccount/namespace"
  tokenPath: "/run/secrets/kubernetes.io/serviceaccount/token"
cu:
  fcuNamespace: "fcu-system"
  publishServerNames: "fcu-if"
  bcsuNamespace: "bcsu-system"
  deploymentReplicas: "1"

configdata: |
  kubernetes:
    admin:
      token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ik5RMEdBbV9KNG9NZy1mVjBDRDBLYmx2aXJITS1WS2tJZFVYV3M0Wmx2WDQifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhZG1pbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJhZG1pbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImJkNWM0NzU4LTY1MGQtNGJiYi05NjY2LWRjZTRiNTM0YjIzZCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTphZG1pbiJ9.J2lxtP5wEYz99RxNwWA0TleOpXRzwR2rNM-Wej2Y99upTiSnlEGKgQIYgnMTFI_XePoDs42FXWTbmztb1OeMMmE1lU7wkjoYok8z7hO1F03C2Yv-jxTpJCo7gCePwNrzLjwQbL7DGAIfTPLAKj1kj0nDEk-p-YGJQGwFF-RdzQ0Wkyt9Sb9QZmk2lrIBpIa6RiGcYNi2Peb9Wn_IUFfqwdV0EL2zktOgEb03jR7-K7YLvgAlbSm2860eEYA4czBBC591kGK1rL9uXw6N0Tnjh9p3ULg0SliN-Bo9eheq0hV_avg386BIBbN7j18M2qGcCSogzoFydB3HQaAxtpI__w
    apiserver:
      domain: lb.kubesphere.local
      address: 192.168.3.31
      port: '6443'

  applications:
    kubesphere:
      webui:
        username: admin
        password: P@88w0rd
      console:
        DNS: ks-console.kubesphere-system
        clusterIP: 10.233.45.27
        type: NodePort
        ports:
        - name: nginx
          port: 80
          nodePort: 30880
      apiserver:
        DNS: ks-apiserver.kubesphere-system
        clusterIP: 10.233.27.166
        type: NodePort
        ports:
        - name: null
          port: 80
          nodePort: 30712
    emqx:
      webui:
        username: admin
        password: public
      api:
        api_key: emqx-operator-controller
        api_secret: u81c5iu3iynm9ycfsafrzymc7xyto8j2cpdoolanzyip8eauvricw2waokigeyin
      dashboard:
        DNS: emqx-cluster-dashboard.emqx-system
        clusterIP: 10.233.61.82
        type: NodePort
        ports:
        - name: dashboard
          port: 18083
          nodePort: 31005
      listeners:
        DNS: emqx-cluster-listeners.emqx-system
        clusterIP: 10.233.18.134
        type: NodePort
        ports:
        - name: ssl-default
          port: 8883
          nodePort: 32159
        - name: tcp-default
          port: 1883
          nodePort: 31465
        - name: ws-default
          port: 8083
          nodePort: 31058
        - name: wss-default
          port: 8084
          nodePort: 31284
    mysql:
      api:
        root_user: root
        root_password: sakila
        root_host: '%'
      apiserver:
        DNS: mysql-innodbcluster.mysql-system
        clusterIP: 10.233.5.9
        type: NodePort
        ports:
        - name: mysql
          port: 3306
          nodePort: 30364
        - name: mysqlx
          port: 33060
          nodePort: 30210
        - name: mysql-alternate
          port: 6446
          nodePort: 32124
        - name: mysqlx-alternate
          port: 6448
          nodePort: 30216
        - name: mysql-ro
          port: 6447
          nodePort: 30271
        - name: mysqlx-ro
          port: 6449
          nodePort: 32053
        - name: mysql-rw-split
          port: 6450
          nodePort: 31138
        - name: router-rest
          port: 8443
          nodePort: 31789
    clickhouse:
      api:
        username: admin
        password: clickhouse
      apiserver:
        DNS: service-clickhouse-cluster.clickhouse-system
        clusterIP: 10.233.49.136
        type: NodePort
        ports:
        - name: http
          port: 8123
          nodePort: 32534
        - name: tcp
          port: 9000
          nodePort: 31159
    redis:
      leader:
        DNS: redis-cluster-leader.redis-system
        clusterIP: 10.233.59.225
        type: ClusterIP
        ports:
        - name: redis-client
          port: 6379
          nodePort: null
      follower:
        DNS: redis-cluster-follower.redis-system
        clusterIP: 10.233.4.176
        type: ClusterIP
        ports:
        - name: redis-client
          port: 6379
          nodePort: null
      leader_external:
        DNS: redis-cluster-leader-external-service.redis-system
        clusterIP: 10.233.21.194
        type: NodePort
        ports:
        - name: client
          port: 6379
          nodePort: 32106
      follower_external:
        DNS: redis-cluster-follower-external-service.redis-system
        clusterIP: 10.233.43.142
        type: NodePort
        ports:
        - name: client
          port: 6379
          nodePort: 30664
    minio:
      webui:
        username: minio
        password: minio123
      api:
        access_key: minio
        secret_key: minio123
      console:
        DNS: myminio-console.minio-system
        clusterIP: 10.233.25.116
        type: NodePort
        ports:
        - name: https-console
          port: 9443
          nodePort: 32068
      apiserver:
        DNS: minio.minio-system
        clusterIP: 10.233.44.37
        type: NodePort
        ports:
        - name: https-minio
          port: 443
          nodePort: 32166
    nacos:
      webui:
        username: nacos
        password: nacos
      apiserver:
        DNS: nacos-cs.nacos-system
        clusterIP: 10.233.43.51
        type: NodePort
        ports:
        - name: http
          port: 8848
          nodePort: 30000
        - name: client-rpc
          port: 9848
          nodePort: 31000
        - name: raft-rpc
          port: 9849
          nodePort: 31001
        - name: old-raft-rpc
          port: 7848
          nodePort: 31002
    harbor:
      domain: tiexiang.io
      webui:
        username: admin
        password: Harbor12345
      dashboard:
        DNS: harbor.harbor-system
        clusterIP: 10.233.24.212
        type: NodePort
        ports:
        - name: http
          port: 80
          nodePort: 30002
    dind:
      apiserver:
        DNS: dind-server.dind-system
        clusterIP: 10.233.18.146
        type: NodePort
        ports:
        - name: docker
          port: 2375
          nodePort: 30011
