# Default values for gateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: tiexiang.io/app/tx-gateway
  pullPolicy: IfNotPresent #Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: v1.0

resources:
  limits:
    memory: 5Gi
  requests:
    memory: 5Gi

service:
  type: NodePort
  port: "31100"
  nodePort: "31007"

nacos:
  group: DEFAULT_GROUP
  namespace: base-test
  server: nacos-cs.nacos-system


