apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: {{ .Values.service.nodePort80 }}
  - name: service-port2
    protocol: TCP
    port: 19000
    targetPort: 19000
    nodePort: {{ .Values.service.nodePort19000 }}
  - name: service-port3
    protocol: TCP
    port: 19001
    targetPort: 19001
    nodePort: {{ .Values.service.nodePort19001 }}
  type: NodePort
