{{- if .Values.imageSecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tx-app.fullname" . }}
  labels:
    {{- include "tx-app.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imageSecret.dockerconfigjson | b64enc | quote }}
{{- end }}