{{- if .Values.imageSecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-imagepull
  labels:
    {{- include "tx-app.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imageSecret.dockerconfigjson }}
{{- end }}
