apiVersion: v1
kind: Service
metadata:
  name: {{ include "tx-app.fullname" . }}
  labels:
    {{- include "tx-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- if .Values.service.ports }}
  {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort | default .name }}
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .name }}
  {{- end }}
  {{- else }}
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.name }}
      protocol: TCP
      name: {{ .Values.service.name }}
  {{- end }}
  selector:
    {{- include "tx-app.selectorLabels" . | nindent 4 }}
