apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svcName }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app:  {{ .Values.svcName }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    nodePort: {{ .Values.service.nodePort }}
  type: {{ .Values.service.type }}
