apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "manager.serviceAccountName" . }}
  labels:
    {{- include "manager.labels" . | nindent 4 }}
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}    
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin
  namespace: {{ .Release.Namespace }}