image:
  repository: 192.168.1.204:30002/app/tx-eeu-test
  tag: v1.0

resources:
  limits:
    memory: 5Gi
  requests:
    memory: 5Gi

nacosConfigMapName: nacos-configmap
containerPort: 31006
replicas: 1
name: tx-eeu
pvcName: eeu-log
volume:
  size: 1Gi
  storageClassName: local