replicaCount: 1

image:
  repository: 192.168.1.204:30002/app/tx-push-test
  tag: v1.0
  pullPolicy: Always

service:
  port: 31009

resources:
  limits:
    memory: 5Gi
  requests:
    memory: 5Gi
name: tx-push
nacosConfigMapName: nacos-configmap  
pvcName: push-log
pvc:
  storageClassName: local
  storage: 1Gi
