replicaCount: 1

image:
  repository: 192.168.1.204:30002/app/tx-auth-test
  tag: v1.0
  pullPolicy: Always

resources:
  limits:
    memory: 5Gi
  requests:
    memory: 5Gi

pvcName: auth-log
volume:
  size: 1Gi
  storageClassName: local

nacosConfigMapName: nacos-configmap
containerPort: 31005