kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: eeu-log
  namespace: manager-system
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tx-eeu
  namespace: manager-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tx-eeu
  template:
    metadata:
      labels:
        app: tx-eeu
    spec:
      containers:
      - name: tx-eeu
        image: 192.168.1.204:30002/app/tx-eeu-test:v1.0
        imagePullPolicy: Always
        command: ["java","-Dfile.encoding=utf-8", "-jar", "/app/tx-eeu.jar"]
        ports:
        - containerPort: 31103
        envFrom:
        - configMapRef:
            name: nacos-configmap
        resources:
          limits:
            memory: 5Gi
          requests:
            memory: 5Gi
        volumeMounts:
        - name: log
          mountPath: /app/logs
      volumes:
        - name: log
          persistentVolumeClaim:
            claimName: eeu-log
