kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gateway-log
  namespace: manager-system
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tx-gateway
  namespace: manager-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tx-gateway
  template:
    metadata:
      labels:
        app: tx-gateway
    spec:
      containers:
      - name: tx-gateway
        image: 192.168.1.204:30002/app/tx-gateway-test:v1.0
        imagePullPolicy: Always
        command: ["java","-Dfile.encoding=utf-8", "-jar", "/app/tx-gateway.jar"]
        ports:
        - containerPort: 31100
        envFrom:
        - configMapRef:
            name: nacos-configmap    
        resources:
          limits:
            memory: 5Gi
          requests:
            memory: 5Gi
        volumeMounts:
          - name: log
            mountPath: /app/logs
      initcontainers:
      - name: gateway-nacos
        image: busybox:1.28
        
      volumes:
        - name: log
          persistentVolumeClaim:
            claimName: gateway-log
---
apiVersion: v1
kind: Service
metadata:
  name: tx-gateway
  namespace: manager-system
spec:
  selector:
    app: tx-gateway
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 31100
    targetPort: 31100
    nodePort: 311000
    clusterIP: 1.2.3.4:3101
  type: NodePort

